<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../RetrievePatientRecord.wsdl"/>
      <rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/RetrievePatientRecord"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../PatientDataService.wsdl"/>
      <rootElement name="PatientDataServiceProcessResponse" namespace="http://stmatthews.hospital.com/patient/PatientDataService"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [FRI MAY 22 01:42:51 PDT 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/PatientDataService/PatientDataService/RetrievePatientRecord"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/RetrievePatientRecord"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:client="http://stmatthews.hospital.com/patient/PatientDataService"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns db plt xsd wsdl client bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap">
  <xsl:template match="/">
    <client:PatientDataServiceProcessResponse>
      <name>
        <xsl:value-of select="concat(/db:OutputParameters/db:GET_PATIENT_RECORD/db:FIRST_NAME,' ',/db:OutputParameters/db:GET_PATIENT_RECORD/db:LAST_NAME)"/>
      </name>
      <initials>
        <xsl:value-of select="/db:OutputParameters/db:GET_PATIENT_RECORD/db:INITIALS"/>
      </initials>
      <gender>
        <xsl:value-of select="/db:OutputParameters/db:GET_PATIENT_RECORD/db:GENDER"/>
      </gender>
      <birthDate>
        <xsl:value-of select="/db:OutputParameters/db:GET_PATIENT_RECORD/db:BIRTH_DATE"/>
      </birthDate>
      <xsl:for-each select="/db:OutputParameters/db:GET_PATIENT_RECORD/db:PHYSICAL_CHARACTERISTICS">
        <client:physicalCharacteristic>
          <dateOfMeasurement>
            <xsl:value-of select="db:PHYSICAL_CHARACTERISTICS_ITEM/db:DATEOFMEASUREMENT"/>
          </dateOfMeasurement>
          <whatWasMeasured>
            <xsl:value-of select="db:PHYSICAL_CHARACTERISTICS_ITEM/db:WHATWASMEASURED"/>
          </whatWasMeasured>
          <measuredValue>
            <xsl:value-of select="db:PHYSICAL_CHARACTERISTICS_ITEM/db:MEASUREDVALUE"/>
          </measuredValue>
          <unitOfMeasurement>
            <xsl:value-of select="db:PHYSICAL_CHARACTERISTICS_ITEM/db:UNITOFMEASUREMENT"/>
          </unitOfMeasurement>
        </client:physicalCharacteristic>
      </xsl:for-each>
    </client:PatientDataServiceProcessResponse>
  </xsl:template>
</xsl:stylesheet>
